version: "3"
services:
  db:
    image: postgres
    volumes:
      - ${PSQL_VOLUME:-./data}:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=pyconkr.production_settings
      - PYCONKR_ADMIN_PASSWORD=${PYCONKR_ADMIN_PASSWORD:-pyconkr}
    command: bash docker-entrypoint.sh
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - db
