version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ${PSQL_VOLUME:-../data}:/var/lib/postgresql/data:z
  api:
    build: .
    restart: always
    environment:
      - PYCONKR_ADMIN_PASSWORD=${PYCONKR_ADMIN_PASSWORD:-pyconkr}
    command: bash docker-entrypoint.sh
    volumes:
      - .:/web
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./static:/static:ro
      - ./config/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - api
