version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ${PSQL_VOLUME:-./postgresql/data}:/var/lib/postgresql/data
  api:
    build: .
    restart: always
    environment:
      - PYCONKR_ADMIN_PASSWORD=${PYCONKR_ADMIN_PASSWORD:-pyconkr}
    volumes:
      - .:/web
      - ${MEDIA_VOLUME:-./media}:/media
      - ${STATIC_VOLUME:-./static}:/static
    ports:
      - ${PORT:-8000}:8000
    depends_on:
      - db
  