version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ${PSQL_VOLUME:-../data}:/var/lib/postgresql/data:z
  api:
    build: .
    restart: always
    environment:
      - PYCONKR_ADMIN_PASSWORD=${PYCONKR_ADMIN_PASSWORD:-pyconkr}
    volumes:
      - .:/web
    ports:
      - 8000:8000
    depends_on:
      - db
  